Finalized wireless
it-dept-cis/Essential-Guide-to-Election-Security pull request #70
Opened 2022-04-22 04:20 UTC by JTAGulous

Finished the wireless BP

Worked on exercising plans

2022-04-22 13:14 UTC, mike-garcia requested changes
@JTAGulous: note the changes to wireless_management maturity1, lines 42-53.

The list of actions from the original was still at the bottom of this bp. I moved them up to maturity1, but if you don't want them, feel free to delete. I'm not advocating for them but didn't want to destroy content if you meant to keep it.

2022-04-22 14:04 UTC, JTAGulous commented on docs/source/BPs/wireless_management.rst
> +#. Use :doc:`the encryption best practice <encryptdataatrest>` for all network traffic.
I don't think we want to talk about encryption at rest for network traffic @mike-garcia! sorry man!

2022-04-29 12:07 UTC, mike-garcia approved these changes

2022-04-29 12:09 UTC, merged

2022-04-29 12:09 UTC, mike-garcia commented
merging to make way for final soft launch review